# Template for Tailscale OAuth credentials
# Copy this file to oauth-secret.yaml and fill in your actual values
# Get these from https://login.tailscale.com/admin/settings/oauth

apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
stringData:
  client_id: "YOUR_OAUTH_CLIENT_ID_HERE"
  client_secret: "YOUR_OAUTH_CLIENT_SECRET_HERE"
